{% set name = "nbparameterise" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1b138747635231489844cded4d80ae3eb8b4c41e566242ab310b55e88c2a2a27

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python >=3.8
    - pip
    - flit-core >=3.2,<4
  run:
    - python >=3.8
    - nbconvert
    - astcheck >=0.3

test:
  imports:
    - nbparameterise

about:
  home: https://github.com/takluyver/nbparameterise
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: This is a tool to run notebooks with input values.
  doc_url: https://github.com/takluyver/nbparameterise
  dev_url: https://github.com/takluyver/nbparameterise

extra:
  recipe-maintainers:
    - kmuehlbauer
