{% set name = "nbparameterise" %}
{% set version = "0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b45e6120af44bc074473843b0c851ca7ae709b311e86d44a4b97798ebc189c9d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python >=3.6
    - pip
    - flit
  run:
    - python >=3.6
    - nbconvert
    - astsearch

test:
  imports:
    - nbparameterise

about:
  home: https://github.com/takluyver/nbparameterise
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: This is a tool to run notebooks with input values.
  doc_url: https://github.com/takluyver/nbparameterise
  dev_url: https://github.com/takluyver/nbparameterise

extra:
  recipe-maintainers:
    - kmuehlbauer
